-- MySQL Script generated by MySQL Workbench
-- Fri May 14 20:35:18 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema helpdesk
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema helpdesk
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `helpdesk` DEFAULT CHARACTER SET latin1 ;
USE `helpdesk` ;

-- -----------------------------------------------------
-- Table `helpdesk`.`usuarioprivilegio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helpdesk`.`usuarioprivilegio` (
  `id` INT(11) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `helpdesk`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helpdesk`.`usuario` (
  `id` INT(11) NOT NULL,
  `apelido` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(32) NOT NULL,
  `cadastro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `privilegio` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `apelido_UNIQUE` (`apelido` ASC) ,
  INDEX `privilegio_id_idx` (`privilegio` ASC) ,
  CONSTRAINT `privilegio_id`
    FOREIGN KEY (`privilegio`)
    REFERENCES `helpdesk`.`usuarioprivilegio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `helpdesk`.`modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helpdesk`.`modulo` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `sigla` CHAR(3) NOT NULL,
  `cadastro` DATETIME NULL DEFAULT NULL,
  `responsavel` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `modulo_responsavel_id_idx` (`responsavel` ASC) ,
  CONSTRAINT `modulo_responsavel_id`
    FOREIGN KEY (`responsavel`)
    REFERENCES `helpdesk`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `helpdesk`.`chamado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helpdesk`.`chamado` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `abertura` DATETIME NOT NULL,
  `usuario` INT(11) NOT NULL,
  `descricao` VARCHAR(200) NULL DEFAULT NULL,
  `encerramento` DATETIME NULL DEFAULT NULL,
  `observacao` TEXT NULL DEFAULT NULL,
  `responsavel` INT(11) NOT NULL,
  `modulo` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `chamado_modulo_id_idx` (`modulo` ASC) ,
  INDEX `chamado_usuario_id_idx` (`usuario` ASC) ,
  INDEX `chamado_responsavel_id_idx` (`responsavel` ASC) ,
  CONSTRAINT `chamado_modulo_id`
    FOREIGN KEY (`modulo`)
    REFERENCES `helpdesk`.`modulo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `chamado_responsavel_id`
    FOREIGN KEY (`responsavel`)
    REFERENCES `helpdesk`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `chamado_usuario_id`
    FOREIGN KEY (`usuario`)
    REFERENCES `helpdesk`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `helpdesk`.`chamadotipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helpdesk`.`chamadotipo` (
  `id` INT(11) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `observacao` TEXT NULL DEFAULT NULL,
  `cadastro` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `helpdesk`.`chamadotramite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helpdesk`.`chamadotramite` (
  `id` INT(11) NOT NULL,
  `chamado` INT(11) NOT NULL,
  `descricao` VARCHAR(300) NOT NULL,
  `usuario` INT(11) NOT NULL,
  `data` DATETIME NOT NULL,
  `destinatario` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `chamado`),
  INDEX `usuario_id_idx` (`usuario` ASC) ,
  INDEX `chamadotramite_destinatario_id_idx` (`destinatario` ASC) ,
  INDEX `chamadotramite_chamado_id_idx` (`chamado` ASC) ,
  CONSTRAINT `chamadotramite_chamado_id`
    FOREIGN KEY (`chamado`)
    REFERENCES `helpdesk`.`chamado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `chamadotramite_destinatario_id`
    FOREIGN KEY (`destinatario`)
    REFERENCES `helpdesk`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `chamadotramite_usuario_id`
    FOREIGN KEY (`usuario`)
    REFERENCES `helpdesk`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `helpdesk`.`situacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helpdesk`.`situacao` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `ehchamado` TINYINT(4) NOT NULL DEFAULT '0',
  `ehchamadotipo` TINYINT(4) NOT NULL DEFAULT '0',
  `ehmodulo` TINYINT(4) NOT NULL DEFAULT '0',
  `ehusuario` TINYINT(4) NOT NULL DEFAULT '0',
  `ehusuarioprivilegio` TINYINT(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

ALTER TABLE `helpdesk`.`chamadotipo` 
CHANGE COLUMN `nome` `descricao` VARCHAR(255) NOT NULL ;

ALTER TABLE `helpdesk`.`modulo` 
CHANGE COLUMN `nome` `descricao` VARCHAR(255) NOT NULL ;

ALTER TABLE `helpdesk`.`situacao` 
CHANGE COLUMN `nome` `descricao` VARCHAR(255) NOT NULL ;

ALTER TABLE `helpdesk`.`usuarioprivilegio` 
CHANGE COLUMN `nome` `descricao` VARCHAR(255) NOT NULL ;

ALTER TABLE `helpdesk`.`modulo` 
CHANGE COLUMN `cadastro` `dataCadastro` DATETIME NULL DEFAULT NULL ;

ALTER TABLE `helpdesk`.`modulo` 
DROP FOREIGN KEY `modulo_responsavel_id`;
ALTER TABLE `helpdesk`.`modulo` 
CHANGE COLUMN `responsavel` `usuarioResponsavel` INT(11) NOT NULL ;
ALTER TABLE `helpdesk`.`modulo` 
ADD CONSTRAINT `modulo_responsavel_id`
  FOREIGN KEY (`usuarioResponsavel`)
  REFERENCES `helpdesk`.`usuario` (`id`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `helpdesk`.`usuario` 
CHANGE COLUMN `cadastro` `dataCadastro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() ;
